import Providers from "@/components/providers";
import { ToastProvider } from "@/components/providers/toast-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'react-loading-skeleton/dist/skeleton.css';
import 'simplebar-react/dist/simplebar.min.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DocsChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
        <ToastProvider />
        {children}
      </body>
      </Providers>
    </html>
  );
}
